#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

cf dev start

# Start gitlab for local debugging
#   see https://docs.gitlab.com/omnibus/docker/
docker rm -f gitlab
#    --restart always \
mkdir -p $HOME/gitlab/{config,logs,data}
#

docker run --detach \
    --hostname local-git.autozone.com \
    --env GITLAB_OMNIBUS_CONFIG="external_url 'http://local-git.autozone.com:9080/'; " \
    --publish 9443:443 --publish 9080:80 --publish 9022:22 \
    --name gitlab \
    --restart always \
    --volume $HOME/gitlab/config:/etc/gitlab \
    --volume $HOME/gitlab/logs:/var/log/gitlab \
    --volume $HOME/gitlab/data:/var/opt/gitlab \
    gitlab/gitlab-ce:latest
