#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

open http://$(grep -oe "[^ ]*local.pcfdev.io" mr-deployer_manifest.yml)
# nodemon ./bin/www
