#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

#cf login -u user -p pass -a api.local.pcfdev.io --skip-ssl-validation
cf login -a api.sys.sandbox.mem.cloud.autozone.com --skip-ssl-validation –sso

if [ -s mr-deployer_manifest.yml ];then
  cf push mr-deployer -c "node ./bin/www"
  cf create-app-manifest mr-deployer
fi

echo "==> App is now ready to go!"
