#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

script/update

curl http://$(grep -oe "[^ ]*local.pcfdev.io" mr-deployer_manifest.yml) >/dev/null 2>&1 && {
    echo "==> Application test passed!"
} || {
    echo "==> Application test failed!"
    false
}